FROM ubuntu:rolling

# no choice to run as root, will powerdown computer
USER root

# hadolint ignore=DL3008,DL3015,SC2086
RUN \
  apt-get -qq update \
  && apt-get -qq install -y --no-install-recommends \
    nut-client \
  && apt-get clean \
  && rm -rf \
    /tmp/* \
    /var/lib/apt/lists/ \
    /var/tmp/*

WORKDIR /config

EXPOSE 3493

COPY ./entrypoint.sh /entrypoint.sh
CMD ["/entrypoint.sh"]