---
name: Build & publish images
on:
  push:
    tags:
      - qqtesting-v*

jobs:
  prepare-matrix:
    runs-on: "ubuntu-latest"
    outputs:
      matrices: ${{ steps.prepare-matrices.outputs.matrices }}
    name: Go - Prepare matrices
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@46e4a501e119d39574a54e53a06c9a705efc55c9 # v1.6.1
        id: app-token
        with:
          app-id: "${{ secrets.RIVERBOT_APP_ID }}"
          private-key: "${{ secrets.RIVERBOT_APP_PRIVATE_KEY }}"

      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: "${{ steps.app-token.outputs.token }}"
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Get dependencies
        run: |
          go mod download

      - name: Matrices
        id: prepare-matrices
        shell: bash
        run: |
          matrices=$(go run cmd/containers.go "all" "true" "false" "stable")
          echo "matrices=${matrices}" >> $GITHUB_OUTPUT
          echo "${matrices}"
  build-and-push-image:
    name: Build ${{ matrix.image.name }} (${{ matrix.image.platform }})
    needs: prepare-matrix
    runs-on: ubuntu-latest
    if: ${{ toJSON(fromJSON(needs.prepare-matrix.outputs.matrices).imagePlatforms) != '[]' && toJSON(fromJSON(needs.prepare-matrix.outputs.matrices).imagePlatforms) != '' }}
    strategy:
      fail-fast: false
      matrix:
        image: ["${{ fromJSON(needs.prepare-matrix.outputs.matrices).imagePlatforms }}"]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log Matrix Input
        shell: bash
        run: |
          cat << EOF
          ${{ toJSON(matrix.image)}}
          EOF
      - name: Validate Matrix Input
        shell: bash
        run: |
          if [[ -z "${{ matrix.image.name }}" ]]; then
              echo "image.name is empty"
              exit 1
          fi
          if [[ -z "${{ matrix.image.version }}" ]]; then
              echo "image.version is empty"
              exit 1
          fi
          if [[ -z "${{ matrix.image.context }}" ]]; then
              echo "image.context is empty"
              exit 1
          fi
          if [[ -z "${{ matrix.image.dockerfile }}" ]]; then
              echo "image.dockerfile is empty"
              exit 1
          fi
          if [[ -z "${{ matrix.image.platform }}" ]]; then
              echo "image.platform is empty"
              exit 1
          fi
          echo "${{ matrix.image.name }}" | grep -E "[a-zA-Z0-9_\.\-]+" || "Image Name is invalid"
          echo "${{ matrix.image.version }}" | grep -E "[a-zA-Z0-9_\.\-]+" || "Image Version is invalid"

      - name: Generate Token
        uses: actions/create-github-app-token@46e4a501e119d39574a54e53a06c9a705efc55c9 # v1.6.1
        id: app-token
        with:
          app-id: "${{ secrets.RIVERBOT_APP_ID }}"
          private-key: "${{ secrets.RIVERBOT_APP_PRIVATE_KEY }}"
          
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: "${{ steps.app-token.outputs.token }}"
          fetch-depth: 1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@31cebacef4805868f9ce9a0cb03ee36c32df2ac4 # v5
        with:
          images: ghcr.io/${{github.repository_owner}}/${{ matrix.image.name }}
          tags: |
            type=raw,value=v${{matrix.image.version}}

      - name: Build and Push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
        
        with:
          build-args: |-
            VERSION=${{ matrix.image.version }}
            REVISION=${{ github.sha }}
            TARGETPLATFORM=${{ matrix.image.platform }}
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: ${{ matrix.image.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}