---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Manual - Build & publish images
on:
  push:
    tags:
      - v*.*.*

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./apps/bitwarden-cli
            image: ghcr.io/${{ github.repository_owner }}/bitwarden-cli
          - context: ./apps/tf-runner-bw
            image: ghcr.io/${{ github.repository_owner }}/tf-runner-bw
          - context: ./apps/protonmail-bridge-docker
            image: ghcr.io/${{ github.repository_owner }}/protonmail-bridge-docker

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: ${{ matrix.image }}

      - name: Build and Push
        uses: docker/build-push-action@94f8f8c2eec4bc3f1d78c1755580779804cb87b2 # v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
